# -*- coding: utf-8 -*-
"""clean_fasta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tzy5mQ5cCceTQ5N89oINhioEE3tZlUhd
"""

from Bio import SeqIO

fasta_file = "MAGE-A3.fasta"

with open(fasta_file, "r") as file:
  for record in SeqIO.parse(file, "fasta"):
    mage_a3_sequence = str(record.seq)

print(mage_a3_sequence)